#########################################Bank Loan###################################################
#require(data.table)
#data <-  as.data.frame(fread("/home/ojasvibhalerao/Desktop/bank_loan.tsv"))

#Step 1) Load the data in
data<-read.table(file = '/users/apple/Desktop/bank_loan.tsv' , sep = '\t' , header= TRUE) 
#Step 2) analyze the variables individually
hist(data$age,xlab="Age",ylab="Number of people")
hist(data$ed,xlab="Years of education",ylab="Number of people")
hist(data$employ)
hist(data$income)
hist(data$debtinc)
hist(data$creddebt)
hist(data$otherdebt)
hist(data$default)

testdata <- subset(data,default==0 | default==1)
show(testdata)

#Step 3: Make a correlation matrix and plot it
M<-cor(testdata,use="complete.obs")
show(M)
library('corrplot') 
corrplot(M, method = "circle") 

#Step 4: PCA on data
library(ggplot2)
pca <- prcomp(data[c(1:8)] , center = TRUE , scale.=TRUE )
summary(pca)

#The eigen values are nothing but normalized sd squared
eigen_data <- pca$sd^2
#Step 5: Find the scree plot to know how many variables to choose
lines(1:8,eigen_data)
#biplot(pca ,  scale=0)
#Step 6 : Infer from loadings
otherpca <- princomp(data[c(1:8)],cor = TRUE)
summary(otherpca)
otherpca$loadings
library(factoextra)
eigen_val <- get_eigenvalue(otherpca)
show(eigen_val)
#SCREE PLOT
fviz_eig(pca, choice = "eigenvalue", addlabels=TRUE)
library(factoextra)
fviz_pca_var(pca)
fviz_pca_ind(pca)
fviz_pca_biplot(pca)
 
```

```{r}