#library(readbulk)
#raw_data <- read_bulk(directory = "/home/ojasvibhalerao/Desktop/pm_data/",
#extension = ".tsv")
#show(raw_data)
#summary(raw_data)
#str(raw_data)
tsv_files <- list.files (path = "/users/apple/Desktop/assign3part2/", 
                         pattern = "*.tsv", 
                         full.names = TRUE)



# (2) Import All csv with 'fread()'
library (data.table)
library(tibble)
DATA_ALL <- as_tibble (rbindlist (lapply (tsv_files, fread)))
show(DATA_ALL)
####Removing useless columns#####
DATA_ALL$customer_id<- NULL
DATA_ALL$response_date <- NULL
DATA_ALL$purchase_date<-NULL
DATA_ALL$product_id<- NULL
DATA_ALL$Rowid<- NULL
DATA_ALL$X_random<- NULL
unique(DATA_ALL$branch)
show(DATA_ALL$gender)
show(DATA_ALL$marital)
show(DATA_ALL)
####Making non numeric values numeric#######
#if male then 0 , female 1

library(plyr)
DATA_ALL$gender <- revalue(DATA_ALL$gender, c("M"=as.integer(0),"F"=as.integer(1)))

#R0 C1 Q2 F3 K4 P5
 library(plyr)
DATA_ALL$branch<-revalue(DATA_ALL$branch,c("Ravensville"= as.integer(0),"Catburg"=1,"Queensbury"=2,"Foxton"=3,"Kingsville"=4,"Princeton"=5))

#Marital status : S0 U1 M2
 library(plyr)
DATA_ALL$marital <- revalue(DATA_ALL$marital, c("S"=0,"U"=1,"M"=2))
DATA_ALL[DATA_ALL$marital == "S"]$marital = 1
show(DATA_ALL$marital)
hist(DATA_ALL$campaign)
hist(DATA_ALL$response)
hist(DATA_ALL$purchase)
hist(DATA_ALL$age)
hist(DATA_ALL$age_youngest_child)
hist(DATA_ALL$`average#balance#feed#index`)
#hist(DATA_ALL$branch)
hist(DATA_ALL$debt_equity)
#hist(DATA_ALL$gender)
hist(DATA_ALL$bad_payment)
hist(DATA_ALL$gold_card)
hist(DATA_ALL$pension_plan)
hist(DATA_ALL$household_debt_to_equity_ratio)
hist(DATA_ALL$income)
#hist(DATA_ALL$marital)
hist(DATA_ALL$members_in_household)
hist(DATA_ALL$months_current_account)
hist(DATA_ALL$months_customer)
hist(DATA_ALL$call_center_contacts)
hist(DATA_ALL$loan_accounts)
hist(DATA_ALL$number_products)
hist(DATA_ALL$number_transactions)
hist(DATA_ALL$non_worker_percentage)
hist(DATA_ALL$white_collar_percentage)
hist(DATA_ALL$rfm_score)

with(DATA_ALL,cor(campaign,purchase))
with(DATA_ALL,cor(response,purchase))
with(DATA_ALL,cor(age,purchase))
with(DATA_ALL,cor(income,purchase))
with(DATA_ALL,cor(gold_card,purchase))
with(DATA_ALL,cor(white_collar_percentage,purchase))
with(DATA_ALL,cor(debt_equity,purchase))
with(DATA_ALL,cor(age_youngest_child,purchase))
with(DATA_ALL,cor(bad_payment,purchase))
with(DATA_ALL,cor(pension_plan,purchase))
with(DATA_ALL,cor(household_debt_to_equity_ratio,purchase))
with(DATA_ALL,cor(members_in_household,purchase))
with(DATA_ALL,cor(months_current_account,purchase))
with(DATA_ALL,cor(months_customer,purchase))
with(DATA_ALL,cor(call_center_contacts,purchase))
with(DATA_ALL,cor(loan_accounts,purchase))
with(DATA_ALL,cor(number_products,purchase))
with(DATA_ALL,cor(number_transactions,purchase))
with(DATA_ALL,cor(non_worker_percentage,purchase))
with(DATA_ALL,cor(rfm_score,purchase))